### ISSUE TITLE
XML parsing error

### ISSUE THREAD

**Issue by aigujin** [gvegayon/googlePublicData#2]
I have successfully built the zip file using version 0.15.7.28 of the package. Upon uploading to google site I get the following error:
XML parsing error. Line: 2, Column: 420: cvc-elt.1: Cannot find the declaration of element 'dspl' with status "Fail".

**Comment by andresterre** [comment]
Hi!! Did you find what was the error ??

**Comment by aigujin** [comment]
No, I couldn't figure it out. I suspect the problem is that Google has changed the XML schema and this package had not been properly updated. I ended up using the Google DSPL tutorial to create my tables.

**Comment by gvegayon** [comment]
Fixed in 367401c08f6b3573dda3bf42f592f580f4bba4e0 Now preparing next cran release
